### ISSUE TITLE
一个小小的Bug在我的Wordpress

### ISSUE THREAD

**Issue by catmangox** [yunify/wp-qingstor#4]
貌似不是bug了，因为在我们所有的wordpress网站中都出现了这个问题。环境为LAMP一键安装包。
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /data/www/www.natureapetfoods.cn/wp-content/plugins/wp-qingstor-master/qingstor.php on line 19 Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /data/www/www.natureapetfoods.cn/wp-content/plugins/wp-qingstor-master/qingstor.php on line 19

**Comment by Xuanwo** [comment]
你好，请问你们是不是直接从 github clone 下来的？有一些依赖没有安装，需要使用 composer install 来安装需要的依赖。

之后我们会 build 好并提供可直接用于安装的 zip 包。

**Comment by catmangox** [comment]
好的，我们会使用Composer重新试试。
